PROJ_NAME = LTDC

SRCS     += stm32f429i_discovery.c
SRCS     += stm32f4xx_hal_msp.c
SRCS     += stm32f4xx_it.c
SRCS     += stm32f4xx_hal.c
SRCS     += stm32f4xx_hal_dma.c
SRCS     += stm32f4xx_hal_flash.c
SRCS     += stm32f4xx_hal_gpio.c
SRCS     += stm32f4xx_hal_i2c.c
SRCS     += stm32f4xx_hal_ltdc.c
SRCS     += stm32f4xx_hal_pwr.c
SRCS     += stm32f4xx_hal_pwr_ex.c
SRCS     += stm32f4xx_hal_rcc.c
SRCS     += stm32f4xx_hal_rcc_ex.c
SRCS     += stm32f4xx_hal_spi.c
SRCS     += stm32f4xx_hal_cortex.c
SRCS     += ili9341/ili9341.c

include ../../Makefile.include
